name: docs

on:
    # 每当 push 到 main 分支时触发部署
    push:
        branches: [main]
    # 手动触发部署
    workflow_dispatch:

jobs:
    docs:
        runs-on: ubuntu-latest

        steps:
            - name: 🏡拉取代码
              uses: actions/checkout@v3
              with:
                  # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
                  fetch-depth: 0

            - name: 💾缓存 Composer 依赖
              uses: actions/cache@v3
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

            - name: 🛠️安装依赖
              uses: php-actions/composer@v6
              with:
                  php_version: "8.1"
                  version: 2

            - name: ❌删除非必要文件
              run: |
                  rm -rf script .gitignore composer.json composer.lock lock.txt upload.md test.env think

            - name: 📦压缩为zip
              run: zip -r LoveCards-${{ github.ref }}.zip ./

            - name: 🎅创建发布并上传压缩包
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  tag_name: ${{ github.ref }}
                  name: 2.2.0[1.0.15] # 记得修改
                  body_path: .gtihub/RELEASE.txt
                  draft: false
                  prerelease: false
                  files: |
                      LoveCards-${{ github.ref }}.zip
                      LICENSE
              env:
                  # @see https://docs.github.com/cn/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
