name: main

on:
    # 每当 push 到 main 分支时触发部署
    push:
        tags:
            - "v*.*.*"
    # 手动触发部署
    workflow_dispatch:

jobs:
    docs:
        runs-on: ubuntu-latest

        steps:
            - name: 🏡拉取代码
              uses: actions/checkout@v3
              with:
                  # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
                  fetch-depth: 0

            - name: 💾缓存 Composer 依赖
              uses: actions/cache@v3
              with:
                  path: /tmp/composer-cache
                  key: ${{ runner.os }}-${{ hashFiles('**/composer.lock') }}

            - name: ✍️提取标签名称
              run: echo "${{ github.ref }}" | cut -d '/' -f 3
              id: tag_name

            - name: 💾保存环境变量
              run: echo "TAG_NAME=${{ steps.tag_name.outputs.stdout }}" >> $GITHUB_ENV

            - name: 🛠️安装依赖
              uses: php-actions/composer@v6
              with:
                  php_version: "8.1"
                  version: 2

            - name: ❌删除非必要文件
              run: |
                  rm -rf .gitignore .github .git DOCKER_ENV docker_tag composer.json composer.lock script lock.txt upload.md test.env think

            - name: 📦压缩为zip
              run: zip -r LoveCards-${{ env.TAG_NAME }}.zip ./
              env:
                  TAG_NAME: ${{ env.TAG_NAME }}

            - name: 🎅创建发布并上传压缩包
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
              with:
                  tag_name: ${{ env.TAG_NAME }}
                  name: 2.2.0[1.0.15] # 记得修改
                  body_path: .github/RELEASE.txt
                  draft: false
                  prerelease: false
                  files: |
                      LoveCards-${{ env.TAG_NAME }}.zip
                      LICENSE
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
